name: GeneralStuff
version: v1.3.5
main: no.dirik.GeneralStuff.Main
api-version: 1.18

commands:
  uwu:
    description: UwU
    usage: /uwu
    permission: GeneralStuff.uwu

  sit:
    description: Makes all tamed animals in a 10x10x10 area sit
    usage: /sit
    permission: GeneralStuff.sit

  stand:
    description: Makes all tamed animals in a 10x10x10 area stand
    usage: /stand
    permission: GeneralStuff.stand

  randompetnames:
    description: Sets a random pet name to your pet
    usage: /randompetnames
    permission: GeneralStuff.RandomPetNames
