name: GeneralStuff
version: 1.0
main: no.dirik.GeneralStuff.Main
api-version: 1.18

commands:
  uwu:
    description: UwU
    usage: /uwu
    permission: UwU.uwu

  sit:
    description: Makes all tamed animals in a 10x10x10 area sit
    usage: /sit
    permission: UwU.sit

  stand:
    description: Makes all tamed animals in a 10x10x10 area stand
    usage: /stand
    permission: UwU.stand

  randompetnames:
    description: Sets a random pet name to your pet
    usage: /randompetnames
    permission: UwU.RandomPetNames
